name: GitHub Actions Test
run-name: ${{ github.actor }} workflow test
on: [push]
jobs:
  testJob:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hi! I'm running because of a ${{ github.event_name }} event."
      - run: echo "Checking out the repository from ${{ github.repository }}."
      - name: Clone repository code
        uses: actions/checkout@v4
      - run: echo "Repository cloned, I think I'm ready. The files look like this:"
      - name: List files
        run: ls  
      # Azure login using GitHub secrets
      - name: Log into the Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}  # Azure credentials stored in GitHub Secrets
          
      - name: Test azure login by getting details
        run: az account show  # Verifying the Azure login

      # Install dependencies
      - name: Install dependencies
        run: pip install -r requirements.txt  # Install the packages from your requirements.txt file

      # Add Azure ML extension for job creation
      - name: add extension
        run:  az extension add -n ml -y
        
      # Create Azure ML Job and capture the job name
      - name: create job
        run: |
          export azure_job_name=$(az ml job create --file production/job1.yaml --resource-group com774-b00953832-rg- --workspace-name com774-b00953832-ws- --query name -o tsv)
          echo "azure_job_name=${azure_job_name}" >> $GITHUB_ENV

      # Wait for the Azure ML job to complete
      - name: Wait for Azure ML retrain Job
        id: wait-for-job
        run: |
          job_status="NotStarted"
          while [ "$job_status" != "Completed" ]; do
            echo "Job Name: $azure_job_name"
            job_status=$(az ml job show --resource-group com774-b00953832-rg- --workspace-name com774-b00953832-ws- --name $azure_job_name --query 'status' -o tsv)
            echo "Job Status: $job_status"
            if [ "$job_status" != "Completed" ]; then
              sleep 60  # Adjust the sleep interval as needed
            fi
          done
        shell: bash
      # Check the final status of the Azure ML job
      - name: Check Azure ML Job Status
        id: check-job-status
        run: |
          job_status=$(az ml job show --resource-group com774-b00953832-rg- --workspace-name com774-b00953832-ws- --name $azure_job_name --query 'status' -o tsv)
          echo "Final Job Status: $job_status"
      # Check the test accuracy and run the job again if the accuracy is less than 95%
      - name: Check Test Accuracy and Run the Job Again
        id: check-accuracy-and-run
        run: |
          threshold=0.95
          if awk -v value="${{ steps.register-and-deploy.outputs.test_accuracy }}" -v threshold="$threshold" 'BEGIN { exit !(value > threshold) }'; then
            echo "The accuracy is greater than $threshold"
            echo "::set-output name=stop_workflow::true"
          else
            echo "The accuracy is less than $threshold"
            echo "Running the training job again with another model"
            echo "::set-output name=stop_workflow::false"
          fi
      - name: Stop Workflow if Needed
        if: steps.check-accuracy-and-run.outputs.stop_workflow == 'true'
        run: exit 0
      # Create Job and capture the job name in an environment variable
      - name: create second job
        run: |
          export azure_job_name=$(az ml job create --file production/job2.yaml --resource-group com774-b00953832-rg- --workspace-name com774-b00953832-ws- --query name -o tsv)
          echo "azure_job_name=${azure_job_name}" >> $GITHUB_ENV
      # Wait for the Azure ML job to complete
      - name: Wait for Azure ML retrain Job
        id: wait-for-retrain-job
        run: |
          job_status="NotStarted"
          while [ "$job_status" != "Completed" ]; do
            echo "Job Name: $azure_job_name"
            job_status=$(az ml job show --resource-group com774-b00953832-rg- --workspace-name com774-b00953832-ws- --name $azure_job_name --query 'status' -o tsv)
            echo "Job Status: $job_status"
            if [ "$job_status" != "Completed" ]; then
              sleep 60  # Adjust the sleep interval as needed
            fi
          done
        shell: bash
      # Check the final status of the Azure ML job
      - name: Check Azure ML Re-Job Status
        id: check-retrain-job-status
        run: |
          job_status=$(az ml job show --resource-group com774-b00953832-rg- --workspace-name com774-b00953832-ws- --name $azure_job_name --query 'status' -o tsv)
          echo "Final Job Status: $job_status"
      # Register, Deploy and Test the model
      - name: Register and Deploy the Model
        id: register-deploy-test
        run: python production/register_deploy_model.py --deploy_name har_blue_deployment --job_name $azure_job_name
      # Disply the test accuracy
      - name: Check Test Accuracy and Dsiplay
        id: check-accuracy-and-display
        run: echo "The test accuracy is ${{ steps.register-deploy-test.outputs.test_accuracy }}"
      # Unit test and Integration test
      - name: Unit Test and Integration Test
        id: unit-test-and-integration-test
        run: python -m unittest test_train test_train_integration          